import bodyComponent, { htmlBodyComponent } from "../components/bodyComponent";
import createTalktrackSection from "../components/talktrackComponent.js.js";

export default function chartsTalktrackSection() {
  return createTalktrackSection({
    heading: "Instructions and Talk Track",
    content: [
      htmlBodyComponent(
        "Atlas Charts",
        `<strong>This section showcases the integration of <b>MongoDB Atlas Charts</b>.</strong><br/><br/>
        <ul>
          <li>These charts update <b>live</b> with the data generated by the simulation.</li>
          <li>Each chart was created with a single click using the <a href='https://www.mongodb.com/products/platform/atlas-charts'>MongoDB Atlas Charts</a> and exported as an <b>iframe</b>.</li>
          <li>All the charts are <b>filtered by session</b>, so each session only sees what's relevant to them and not for other sessions.</li>
          </ul>
        <br/>
        <em>Atlas Charts provide a powerful and interactive way to visualize your data in real time.</em>`
      ),
    ],
  });
}