services:
  my-agentic-workflow-front:
    build:
      context: ./
      dockerfile: Dockerfile.frontend
    image: my-agentic-workflow-front:latest
    ports:
      - "3000:3000"
    # restart: always
    container_name: my-agentic-workflow-front-container
    env_file:
      - ./frontend/.env
    networks:  
      - simulation-network 
    

networks:  
  simulation-network:  
    external: true  